### ISSUE TITLE
Data Preprocessing File??

### ISSUE THREAD

**Issue by NomiMalik0207** [IvonaTau/emotionaldan#1]
where i can get this file. There is nothig like train.txt in your repo. Please help me to 

To read the training data run:

ReadList('train.txt', 'Trainset', isTrainSet=True), where train.txt is in the following format: path_to_jpg_image class_label

**Comment by IvonaTau** [comment]
This is the list of files your are going to use for training. We trained our model on AffectNet (http://mohammadmahoor.com/affectnet/). This dataset is available upon request, so we can not share the data. Please follow the download instructions from the link.

**Comment by IvonaTau** [comment]
`train.txt` is in the following format: `path_to_img     label`, e.g:

```
image_2.jpg 2
image_3.jpg 1
image_4.jpg 1
image_5.jpg 2
image_6.jpg 2
```

**Comment by NomiMalik0207** [comment]
why you didn't share the preprocessing file of data preprocessing?
